name: 'Dependencies Outdater'
description: 'Will automatically check your dependencies and look for latest updates.'
branding:
  icon: align-center
  color: green
inputs:
  access_token:
    description: Github Access Token to access and modify your pr's label
    required: true
  language:
    description: Which language you are tring to use for dependencies checking.
    required: false
    default: nodejs
  package_manager:
    description: Which package manager will be used
    default: yarn
    required: false
runs:
  using: 'node16'
  pre: "scripts/pre-run.js"
  main: 'dist/index.js'
  